### ISSUE TITLE
What should be the path?

### ISSUE THREAD

**Issue by ukwiz** [roryg/ElementHelper#41]
As there is no documentation for 2.0, I am having difficulty in setting up the directory structure. I have tried putting a chunk.html into /site/elements/chunks, but nothing happens - even after clearing cache. Similarly with assets/site/elements/chunks.

I am on modx 2.4.2 and elementhelper-2.0.0-alpha-3

**Comment by roryg** [comment]
Hi Ukwiz,

You need to have `site/elements/chunks` in the root of your modx install and any chunks or templates should use the `.tpl` file type. Hope that helps! :)

**Comment by ukwiz** [comment]
Thanks Rory, that did the trick. Regards David
