### ISSUE TITLE
System Setting elementhelper.element_history does not exist

### ISSUE THREAD

**Issue by ghost** [roryg/ElementHelper#43]
Cascading fatal errors because elementhelper.element_history setting does not exist

MODX 2.5.0
ElementHelper 2.0.0 alpha patched from gist per this comment https://github.com/roryg/ElementHelper/issues/38#issuecomment-215602148

**Comment by JayCarney** [comment]
The patch in the gist is for elementhelper 1.3.3

**Comment by ghost** [comment]
Well, that would certainly account for it!
