### ISSUE TITLE
Installable in MODX Extras But Doesn't Work?!

### ISSUE THREAD

**Issue by dinglestein** [roryg/ElementHelper#45]
I just installed it and tested it but it does not seem to work :(

Has anyone else managed to make the extra work?!

This is the most anticipated MODX extra!!! 100%

**Comment by roryg** [comment]
Hi, which versions of Modx/Elementhelper are you using? I used the latest alpha-3 version here - https://www.dropbox.com/s/5x627zz1cnq1rxw/elementhelper-2.0.0-alpha-3.transport.zip?dl=0 - with Modx 2.5.0 last month and it worked without any issues.
